### PR TITLE
[Fix] `order`: leave more space in rankings for consecutive path groups 

### LINKED ISSUE #2494: `import/order` does not respect consecutive `pathGroups` when 9 or 10 groups are defined
Import types can be assigned the same `rank` when using 1 or more `after` `patterns` and 9-10 `before` `patterns` on consecutive import types. 

[Repro](https://github.com/Pearce-Ropion/eslint-plugin-import-order-error)

Given the following config
```js
module.exports = {
  parser: '@babel/eslint-parser',
  parserOptions: {
    requireConfigFile: false,
  },
  settings: {
    'import/internal-regex': '^(a|b|c|d|e|f|g|h|i|j|k|l|m)(\\/|$)',
  },
  plugins: ['import'],
  rules: {
    'import/order': [
      'error',
      {
        groups: ['builtin', 'external', 'internal', 'parent', ['sibling', 'index']],
        pathGroups: [
          { pattern: '@namespace/**', group: 'external', position: 'after' }, 
          { pattern: 'a', group: 'internal', position: 'before' },
          { pattern: 'b', group: 'internal', position: 'before' },
          { pattern: 'c', group: 'internal', position: 'before' },
          { pattern: 'd', group: 'internal', position: 'before' },
          { pattern: 'e', group: 'internal', position: 'before' },
          { pattern: 'f', group: 'internal', position: 'before' },
          { pattern: 'g', group: 'internal', position: 'before' },
          { pattern: 'h', group: 'internal', position: 'before' },
          { pattern: 'i', group: 'internal', position: 'before' },
        ],
        pathGroupsExcludedImportTypes: ['builtin'],
        'newlines-between': 'always',
      },
    ],
  },
};
```

The above config will result in the following file. With the 9 `before` `patterns`, `a` gets grouped with the `@namespace` imports. This **doesn't** happen with 8 or 11 `before` `patterns`.

```js
// Notice how `import { a } from 'a'` gets grouped with the `@namespace` imports.

import React from 'react';

import { bar } from '@namespace/bar';
import { foo } from '@namespace/foo';
import { a } from 'a';

import { b } from 'b';

import { c } from 'c';

import { d } from 'd';

import { e } from 'e';

import { f } from 'f';

import { g } from 'g';

import { h } from 'h';

import { i } from 'i';

import { j } from 'j';
import { k } from 'k';
import { l } from 'l';
import { m } from 'm';

import parent from '../parent';

import sibling from './sibling';
```

The expected output with 9 `before` `patterns` should be :
```js
import React from 'react';

import { bar } from '@namespace/bar';
import { foo } from '@namespace/foo';

import { a } from 'a';

import { b } from 'b';

import { c } from 'c';

import { d } from 'd';

import { e } from 'e';

import { f } from 'f';

import { g } from 'g';

import { h } from 'h';

import { i } from 'i';

import { j } from 'j';
import { k } from 'k';
import { l } from 'l';
import { m } from 'm';

import parent from '../parent';

import sibling from './sibling';
```

Similarly, with the 10 `before` `patterns`, `a` gets grouped with the `external` imports. This **doesn't** happen with 8 or 11 `before` `patterns`.

<details>

```js
// Notice how `import { a } from 'a'` gets grouped with the `external` imports.

import React from 'react';
import { a } from 'a';

import { bar } from '@namespace/bar';
import { foo } from '@namespace/foo';
import { b } from 'b';

import { c } from 'c';

import { d } from 'd';

import { e } from 'e';

import { f } from 'f';

import { g } from 'g';

import { h } from 'h';

import { i } from 'i';

import { j } from 'j';

import { k } from 'k';
import { l } from 'l';
import { m } from 'm';

import parent from '../parent';

import sibling from './sibling';
```
</details>

---

I also tried logging the generated rankings from `computeRank` for each amount of `before` `patterns`.

<details>
<summary>8  pathGroups</summary>

```
react external 1
@namespace/bar external 1.1
@namespace/foo external 1.1
a internal 1.2
b internal 1.3
c internal 1.4
d internal 1.5
e internal 1.6
f internal 1.7
g internal 1.8
h internal 1.9
i internal 2
j internal 2
k internal 2
l internal 2
m internal 2
../parent parent 3
./sibling sibling 4

```
</details>

<details>
<summary>9  pathGroups</summary>

```
react external 1
@namespace/bar external 1.1
@namespace/foo external 1.1
a internal 1.1
b internal 1.2
c internal 1.3
d internal 1.4
e internal 1.5
f internal 1.6
g internal 1.7
h internal 1.8
i internal 1.9
j internal 2
k internal 2
l internal 2
m internal 2
../parent parent 3
./sibling sibling 4
```

 </details>

<details>
<summary>10  pathGroups</summary>

```
a internal 1
react external 1
@namespace/bar external 1.1
@namespace/foo external 1.1
b internal 1.1
c internal 1.2
d internal 1.3
e internal 1.4
f internal 1.5
g internal 1.6
h internal 1.7
i internal 1.8
j internal 1.9
k internal 2
l internal 2
m internal 2
../parent parent 3
./sibling sibling 4
```

</details>

<details>
<summary>11  pathGroups</summary>

```
react external 1
@namespace/bar external 1.01
@namespace/foo external 1.01
a internal 1.89
b internal 1.9
c internal 1.91
d internal 1.92
e internal 1.93
f internal 1.94
g internal 1.95
h internal 1.96
i internal 1.97
j internal 1.98
k internal 1.99
l internal 2
m internal 2
../parent parent 3
./sibling sibling 4
```

</details>

---

I had a lot of trouble coming up with a generalized description for this since its a very specific issue.

### PR DESCRIPTION
**Pull request by Pearce-Ropion**
Resolves #2494 

Creates more space (numerically) between consecutive groups to allow for what would have been overlapping path groups.

The issue occurs when there are enough (9-10) before/after `pathGroups` in consecutive `groups` where the rankings start to overlap with the previous/next group. See the repro in #2494 for one example of this.

I think a better fix would be to rework some of the ranking logic in `convertPathGroupsForRanks`. However, this change was a non-invasive easy workaround that doesn't introduce any regressions (as far as I can tell).

### CODE REVIEW

File: tests/src/rules/order.js [hunk 1]
```diff
@@ -2099,6 +2099,74 @@ ruleTester.run('order', rule, {
...
+            { pattern: 'i', group: 'internal', position: 'before' },
+          ],
+          'newlines-between': 'always',
+          pathGroupsExcludedImportTypes: ['builtin'],
+        },
+      ],
+      settings: {
+        'import/internal-regex': '^(a|b|c|d|e|f|g|h|i|j|k)(\\/|$)',
+      },
+      errors: new Array(11).fill('There should be at least one empty line between import groups'),
```
Comment (ljharb) [inline tests/src/rules/order.js:2168]: `new Array` should never, ever be used, even in test code
```suggestion
      errors: Array.from({ length: 11 }, () => 'There should be at least one empty line between import groups'),
```

**Review by ljharb — COMMENTED** [review]
Seems pretty solid!

File: tests/src/rules/order.js (hunk 1 above)
Comment (Pearce-Ropion) [reply tests/src/rules/order.js]: Hmm, TIL 👍

**Review by ljharb — APPROVED** [review]
