### PR TITLE
[Fix] `newline-after-import`: fix `considerComments` option when require

### LINKED ISSUE #2905: [import/newline-after-import] `considerComments` not working with `require` statements
The option `considerComments` doesn't seem to work with `require` statements. For example, with the following configuration:

```js
"import/newline-after-import": ["warn", { count: 2, considerComments: true }]
```

These are considered valid:

```js
const fs = require("fs");

// Test comment
const FOO = true;
```
```js
const fs = require("fs");
/**
 * Test comment
 */
const FOO = true;
```

While they should be:
```js
const fs = require("fs");


// Test comment
const FOO = true;
```
```js
const fs = require("fs");


/**
 * Test comment
 */
const FOO = true;
```

It works as it should with `import` statements.

### PR DESCRIPTION
**Pull request by developer-bandi**
fix #2905 

- new var in test file  use multiple space when require
- fix or remove invalid test cases
- add feature considerComments is applied normally when use require

### CODE REVIEW

File: src/rules/newline-after-import.js [hunk 1]
```diff
@@ -140,7 +140,7 @@ module.exports = {
             line: node.loc.end.line,
             column,
           },
-          message: `Expected ${options.count} empty line${options.count > 1 ? 's' : ''} after import statement not followed by another import.`,
+          message: `Expected ${options.count} empty line${options.count > 1 ? 's' : ''} after ${type} statement not followed by another ${type}.`,
```
Comment (ljharb) [inline src/rules/newline-after-import.js:143]: can we make `type` (and while we're at it, the count and the pluralization) part of the `data` instead of interpolated in?

it'd also be fine to do this as a followup.

File: tests/src/rules/newline-after-import.js [hunk 2]
```diff
@@ -202,7 +203,7 @@ ruleTester.run('newline-after-import', require('rules/newline-after-import'), {
       options: [{ count: 4, exactCount: true }],
     },
     {
-      code: `var foo = require('foo-module');\n\n\n\n// Some random comment\nvar foo = 'bar';`,
+      code: `var foo = require('foo-module');\n\n\n\n\n// Some random comment\nvar foo = 'bar';`,
```
Comment (ljharb) [inline tests/src/rules/newline-after-import.js:206]: the "count" is set to 4, so it's surprising to me that this would have 5 newlines. can you explain?

File: tests/src/rules/newline-after-import.js [hunk 3]
```diff
@@ -852,14 +861,26 @@ ruleTester.run('newline-after-import', require('rules/newline-after-import'), {
...
+      code: `var foo = require('foo-module');\n\n/**\n * Test comment\n */\nvar foo = 'bar';`,
+      output: `var foo = require('foo-module');\n\n\n/**\n * Test comment\n */\nvar foo = 'bar';`,
       errors: [{
         line: 1,
         column: 1,
-        message: 'Expected 2 empty lines after require statement not followed by another require.',
+        message: REQUIRE_ERROR_MESSAGE_MULTIPLE(2),
       }],
-      parserOptions: { ecmaVersion: 2015 },
+      parserOptions: { ecmaVersion: 2015, sourceType: 'module' },
```
Comment (ljharb) [inline tests/src/rules/newline-after-import.js:882]: why is sourceType module needed here? this is CJS, not ESM.
```suggestion
      parserOptions: { ecmaVersion: 2015 },
```

Comment (developer-bandi) [reply tests/src/rules/newline-after-import.js:882]: this is my mistake. I will remove the module option.

File: tests/src/rules/newline-after-import.js (hunk 2 above)
Comment (developer-bandi) [reply tests/src/rules/newline-after-import.js:206]: If we print code above, it will look like this:
```javascript
var foo = require('foo-module');




// Some random comment
var foo = 'bar';
```
In other words, five newlines are needed to create four valid blank lines for the option.

File: src/rules/newline-after-import.js (hunk 1 above)
Comment (developer-bandi) [reply src/rules/newline-after-import.js:143]: I'm not sure I understand exactly. Is it correct to say that create a function that params are count ,type and return the created message and apply it to other messages? below is example code

```
function example(count, type){
    return  `Expected ${options.count} empty line${options.count > 1 ? 's' : ''} after ${type} statement not followed by another ${type}.`,
}
....
messages:example(options.count,type)

```

File: tests/src/rules/newline-after-import.js (hunk 2 above)
Comment (ljharb) [reply tests/src/rules/newline-after-import.js:206]: aha, thanks, that makes sende

File: src/rules/newline-after-import.js (hunk 1 above)
Comment (developer-bandi) [reply src/rules/newline-after-import.js:143]: @ljharb If my understanding is correct, I will proceed in the follow-up PR.

Comment (ljharb) [reply src/rules/newline-after-import.js:143]: No, not a function - using eslint's own message interpolation format; no function required. A followup is fine.

File: tests/src/rules/newline-after-import.js [hunk 4]
```diff
@@ -852,14 +861,26 @@ ruleTester.run('newline-after-import', require('rules/newline-after-import'), {
       parserOptions: { ecmaVersion: 2015, considerComments: true, sourceType: 'module' },
     },
     {
-      code: `const foo = require('foo');\n\n\n// some random comment\nconst bar = function() {};`,
-      options: [{ count: 2, exactCount: true, considerComments: true }],
```
Comment (ljharb) [inline tests/src/rules/newline-after-import.js:856]: can we keep this existing test case, to ensure it's not a breaking change?

File: src/rules/newline-after-import.js (hunk 1 above)
Comment (developer-bandi) [reply src/rules/newline-after-import.js:143]: Ah, I understand. Are you referring to the code format below? (example is `consistent-type-specifier-style` rule)

```javascript
context.report({
....
            message: 'Prefer using a top-level {{kind}}-only import instead of inline {{kind}} specifiers.',
            data: {
              kind: kind.join('/'),
            },
          }
 ....
```

File: tests/src/rules/newline-after-import.js (hunk 4 above)
Comment (developer-bandi) [reply tests/src/rules/newline-after-import.js:856]: This test case is valid, so if we want to keep it, I think the test case should be included in the valid array. Is it okay to do this?

File: src/rules/newline-after-import.js (hunk 1 above)
Comment (ljharb) [reply src/rules/newline-after-import.js:143]: yes, exactly that.

Comment (developer-bandi) [reply src/rules/newline-after-import.js:143]: Thank you. I will proceed with the follow-up work as mentioned above.

File: tests/src/rules/newline-after-import.js (hunk 4 above)
Comment (ljharb) [reply tests/src/rules/newline-after-import.js:856]: Sure, that's fine - moving the test shows it's a bug fix.

Comment (developer-bandi) [reply tests/src/rules/newline-after-import.js:856]: thanks, I applied it.

**Comment by Arkellys** [comment]
Any news about this?

**Comment by developer-bandi** [comment]
@Arkellys for merge, i wait code review. @ljharb Could you please take a look?

**Review by ljharb — APPROVED** [review]
LGTM, thanks
