### PR TITLE
[Fix] `extensions`: handle `.` and `..` properly

### LINKED ISSUE #2777: [import/extensions] Doesn't error on . or ..
I have this rule configured like so:
```javascript
'import/extensions': ['error', 'ignorePackages'],
```

With this configuration, the following is flagged as an error:
```javascript
import { Something } from './LocalFolderWithIndexfile'
```

However, the following is not flagged as an error, but I believe it should be:
```javascript
import { Something } from '.'
```

The only difference between the two is where in the file tree the importing file sits. As a workaround, one can supplement this rule with the general `no-restricted-imports` rule like this:
```javascript
'no-restricted-imports': ['error',
  {
    paths: [
      {
        name: '..',
        message: 'Import from ../index.js instead.',
      },
      {
        name: '.',
        message: 'Import from ./index.js instead.',
      },
    ],
  },
],
```

Apologies if this has already been filed. I found it really hard to search for

### PR DESCRIPTION
**Pull request by benasher44**
The issue was `isExternalRootModule` was returning `true` for these, since they had no `/` in them. This fixes that.

Closes #2777

### CODE REVIEW

**Review by ljharb — COMMENTED** [review]
Can we also add some test cases with the "always" option where `.` and `..` refer to dirs with package.json, and show that these don't error?

**Comment by ljharb** [comment]
Ideally I'd like this PR to either add tests documenting the current behavior (with a TODO comment if it's broken), or, tests matching the desired behavior and fixes for it.

While `ignorePackages` was intended to cover things in `node_modules`, i think it actually makes sense to cover a relative dir with a `package.json` as well. I'm wondering how large a change that would be.

**Comment by benasher44** [comment]
I added tests that show the current behavior (says extensions are required when they shouldn't be)

File: tests/src/rules/extensions.js [hunk 1]
```diff
@@ -594,6 +614,35 @@ ruleTester.run('extensions', rule, {
...
+        },
+      ],
+    }),
+    // TODO: properly ignore packages resolved via relative imports
+    test({
+      code: [
+        'import * as test from ".."',
+      ].join('\n'),
+      filename: testFilePath('./internal-modules/plugins/plugin.js'),
+      options: [ 'ignorePackages' ],
```
Comment (benasher44) [inline tests/src/rules/extensions.js:638]: I'm not sure about whether these should be `always`. I think with `ignorePackages` it should definitely not error, so it makes for a less ambiguous test case.

In the always + relative case it's a bit more ambiguous to me, since if we assume the relative path is in your project, you might have this set to `always` because you always want someone to choose a file (within the project).

**Comment by benasher44** [comment]
Any tips on what to do about the semver module not found errors from appveyor?

File: tests/src/rules/extensions.js (hunk 1 above)
Comment (ljharb) [reply tests/src/rules/extensions.js:638]: I'm not sure what to do here, tbh.

Comment (ljharb) [reply tests/src/rules/extensions.js:638]: I'm going to merge this, and please file followup issues and/or PRs :-)

**Comment by benasher44** [comment]
Thank you!
