### PR TITLE
`import/order` Fix group ranks order when alphabetizing

### LINKED ISSUE #2671: [import/order] Potential regression in `sibling` and `parent` behavior
We have a bit of a complex `import/order` config and are seeing some new weird behavior with ordering on the `sibling` and `parent` groups on `eslint-plugin-import@2.27.4`:

```js
'import/order': [
  'error',
  {
    alphabetize: {
      order: 'asc',
      caseInsensitive: true,
    },
    groups: ['type', 'builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object'],
    'newlines-between': 'always',
    pathGroups: [
      { pattern: '@Hub', group: 'external', position: 'after' },
      { pattern: '@Hub/**', group: 'external', position: 'after' },
      { pattern: '@Dash/**', group: 'external', position: 'after' },
      { pattern: '@core/**', group: 'external', position: 'after' },
      { pattern: '@routes/**', group: 'external', position: 'after' },
      { pattern: '@ui', group: 'external', position: 'after' },
      { pattern: '@ui/**', group: 'external', position: 'after' },
    ],
    pathGroupsExcludedImportTypes: ['@Hub', '@Dash', '@core', '@routes', '@ui'],
    warnOnUnassignedImports: true,
  },
],
```

Here's what our code looks like on `eslint-plugin-import@2.26.0`:

```js
import React from 'react';

import Flex from '@ui/Flex';
import Menu, { MenuItem, MenuDivider } from '@ui/Menu';

import { isPolymorphic } from '../../utils';

import classes from './style.module.scss';
import './style.scss';
```

And it wants it to be now:

```js
import React from 'react';

import Flex from '@ui/Flex';
import Menu, { MenuItem, MenuDivider } from '@ui/Menu';

import classes from './style.module.scss';
import './style.scss';

import { isPolymorphic } from '../../utils';
```

However if I swap the the order of `parent` and `sibling` in the config to this then the behavior we were seeing on v2.26.0 remains:

```js
groups: ['type', 'builtin', 'external', 'internal', 'sibling', 'parent', 'index', 'object']
```

### PR DESCRIPTION
**Pull request by Pearce-Ropion**
Resolves #2671 

Correctly sorts `groupRanks` in numerical order when alphabetizing. This bug would occur for groups where the `rank` overflowed to double digits (eg. `"10"` is sorted before `"4"`). This is a bug with the original code and not necessarily caused by #2506. There just previously wasn't a case where enough groups were added to get to the double digit ranks.

The test case I made for this is similar to the example case shown in #2671 but it isn't the most general test case. It's just a case that would fail without this change.

I also went ahead and added a description comment to my previous PR's test case since it was missing one

### CODE REVIEW

**Comment by ljharb** [comment]
A test case that fails without this fix is definitely necessary, otherwise we'll just break it again in the future :-)

**Comment by ljharb** [comment]
Unfortunately this test case passes on main :-/ do you have one that fails on main?

**Comment by Pearce-Ropion** [comment]
> Unfortunately this test case passes on main :-/ do you have one that fails on main?

Huh...

**Comment by Pearce-Ropion** [comment]
> Unfortunately this test case passes on main :-/ do you have one that fails on main?

Ok, this should be working now. I tested it on `main` too to make sure it failed. I forgot that the only way to get the ranks into the double digits is if you have a lot of `groups`. Thats what I get for trying to cleanup a test case to make it presentable...

File: src/rules/order.js [hunk 1]
```diff
@@ -334,18 +334,21 @@ function mutateRanksToAlphabetize(imported, alphabetizeOptions) {
     return acc;
   }, {});
 
-  const groupRanks = Object.keys(groupedByRanks);
-
   const sorterFn = getSorter(alphabetizeOptions);
 
+  // sort group keys so that they can be iterated on in order
+  const groupRanks = Object.keys(groupedByRanks).sort(function (a, b) {
+    return parseFloat(a) - parseFloat(b);
```
Comment (ljharb) [inline src/rules/order.js:341]:
```suggestion
    return a - b;
```
this should be sufficient

**Review by ljharb — APPROVED** [review]
Looks great!
