### PR TITLE
[Fix] `named`/`ExportMap`: handle named imports from CJS modules that use dynamic import

### LINKED ISSUE #2294: import/named falsely reports import as not found (regression in 2.25)
eslint-plugin-import version: 2.25.0 and 2.25.2
eslint version: 7.32 and 8.1
Reproduction repo: https://github.com/ludofischer/eslint-plugin-import-error-demo

When using the `optimize` named import from the [svgo](https://github.com/svg/svgo) 2.8 library, since 2.25 eslint-plugin-import reports
```
error  optimize not found in 'svgo'  import/named
```
while the import was correctly handled as valid in eslint-plugin-import 2.24. svgo uses CommonJS with just a `main` `package.json` field that points to this file: https://github.com/svg/svgo/blob/master/lib/svgo-node.js

### PR DESCRIPTION
**Pull request by ludofischer**
Fix #2294
* Modify `ExportMap` to track whether the module is unambiguously ES6
* Add tests for named import with `import` as `require()`

### Proposed solution
Mark ambiguous (i.e. not unambiguously ESM) modules that contain dynamic import()
so that they can be ignored like other ambiguous modules when analysing named imports.

Previous to https://github.com/import-js/eslint-plugin-import/commit/7c382f02a6cafe676ee754a896092040dad8daf6 this was not necessary because a `null` ExportMap was returned for all ambiguous modules.

### Alternatives
Parse the CommonJS exports instead of ignoring the CommonJS modules. Rejected because analysingg CommonJS exports seems out of scope of this plugin.

### CODE REVIEW

File: src/ExportMap.js [hunk 1]
```diff
@@ -43,6 +43,13 @@ export default class ExportMap {
      */
     this.imports = new Map();
     this.errors = [];
+    /**
+     * true when we are still unsure if
+     * the module is ESM, happens when the module
+     * contains dynamic `import()` but no other
+     * ESM import/export
+     */
+    this.maybeNotEsm = false;
```
Comment (ljharb) [inline src/ExportMap.js:52]: "containing dynamic import" tells us nothing, so it'd be find to maybe name this `this.parseGoal`?

that way it could be set to `'ambiguous'` by default, `'Module'` when it finds an export or an import, `Script` when it finds a `with` statement, etc.

File: src/ExportMap.js [hunk 2]
```diff
@@ -406,7 +413,8 @@ ExportMap.parse = function (path, content, context) {
     },
   });
 
-  if (!unambiguous.isModule(ast) && !hasDynamicImports) return null;
+  const maybeNotEsm = !unambiguous.isModule(ast);
+  if (maybeNotEsm && !hasDynamicImports) return null;
```
Comment (ljharb) [inline src/ExportMap.js:417]: it could still be ESM in this case - it depends on what the eslint config has set for `sourceType`.

**Review by ljharb — COMMENTED** [review]
Tests look good!

File: src/ExportMap.js (hunk 1 above)
Comment (ludofischer) [reply src/ExportMap.js:52]: Sounds reasonable. Basically make the three types of results explicit.

Comment (ludofischer) [reply src/ExportMap.js:52]: But what happens in the cases where the code returns a `null` `ExportMap` currently? Should  it return an `ExportMap` with `parseGoal` set to `Script` as a sort of null object?

File: src/ExportMap.js (hunk 2 above)
Comment (ludofischer) [reply src/ExportMap.js:417]: Do you suggest adding a check on the `sourceType` value in the config? I don't see any code checking this at the moment, but maybe I am not looking for it correctly.

File: src/ExportMap.js (hunk 1 above)
Comment (ljharb) [reply src/ExportMap.js:52]: That seems reasonable - to always have a consistent type returned.

File: src/ExportMap.js (hunk 2 above)
Comment (ljharb) [reply src/ExportMap.js:417]: You're right, we probably aren't checking that. I think that specifically when the goal is ambiguous, we should defer to the config (and add that checking)

**Comment by ludofischer** [comment]
I've applied your suggestion of turning `maybeNotEsm` into a `parseGoal` field. Is there another refactor you had in mind where this `parseGoal` should be used? Another thing that was on my mind is that the `default` rule might also fail in a similar case.

**Comment by ljharb** [comment]
I'm mainly hoping that we can get these kinds of helpers in a place where it becomes trivial to support CJS files as well as ESM files.

What are your thoughts about having an "empty" ExportsMap instead of `null` for a CJS file without dynamic imports?

**Comment by ludofischer** [comment]
> What are your thoughts about having an "empty" ExportsMap instead of `null` for a CJS file without dynamic imports?

I need to take a longer look at the code. My instinct would be that it increases the risk of breaking something else as we'll miss one spot that's relying on the ExportsMap being `null`.

**Comment by ljharb** [comment]
Fair enough, let's do that in a follow-up PR then.

**Review by ljharb — APPROVED** [review]

**Comment by ludofischer** [comment]
> Fair enough, let's do that in a follow-up PR then.

I feel like I am missing some context to make a follow-up. I've looked at the implementation for the rules some more and I've also looked at the issues. I cannot find  case where returning empty ExportMap from a CJS file would make a difference:
1. it would not get rid of returned `null` since `ExportMap.get()` returns `null` when the file is ignored or has an invalid extension according to the config
2. all of `dependencies`, `imports`, `errors` would be empty, it would be the same as skipping processing completely, which already happens when `ExportMap` is `null`

On an unrelated note, have you thought about using issue templates to require a link to a reproduction? I've got the impression that a lot of open issues are unactionable because they lack a reproduction.

**Comment by ljharb** [comment]
@ludofischer i'm mainly thinking that it'd make it clearer for rules to use ExportsMap - since CJS Scripts have a dep graph too, and this plugin should support them.

As for an issue template, I'd be happy to look at a PR that added one :-)
