### PR TITLE
[Fix] ExportMap: Add default export when esModuleInterop is true and anything is exported

### LINKED ISSUE #2183: [import/default] - false negative for react-test-renderer
I'm doing this:
```
import reactTestRenderer from 'react-test-renderer';
```

Getting this:
```
No default export found in imported module "react-test-renderer". eslint (import/default)
```

Using these types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-test-renderer/index.d.ts

And I have `esModuleInterop` in my tsconfig, so this should not throw error (thanks to https://github.com/import-js/eslint-plugin-import/pull/1689)

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
This PR aims to fix #2183 by adding default export if anything is exported and `esModuleInterop` is set to true.

This probably should've been done in #1689 that I originally opened to add `esModuleInterop` support.

### CODE REVIEW

File: src/ExportMap.js [hunk 1]
```diff
@@ -606,8 +605,11 @@ ExportMap.parse = function (path, content, context) {
         m.namespace.set('default', captureDoc(source, docStyleParsers, n));
         return;
       }
-      if (isEsModuleInteropTrue) {
-        m.namespace.set('default', {});
+      if (
+        isEsModuleInteropTrue && // esModuleInterop is on in tsconfig
+        !m.namespace.has('default') // and default isn't added already
```
Comment (ljharb) [inline src/ExportMap.js:610]:
```suggestion
        isEsModuleInteropTrue // esModuleInterop is on in tsconfig
        && !m.namespace.has('default') // and default isn't added already
```

File: src/ExportMap.js [hunk 2]
```diff
@@ -645,6 +647,14 @@ ExportMap.parse = function (path, content, context) {
     }
   });
 
+  if (
+    isEsModuleInteropTrue // esModuleInterop is on in tsconfig
+     && m.namespace.size > 0 // anything is exported
+      && !m.namespace.has('default') // and default isn't added already
```
Comment (ljharb) [inline src/ExportMap.js:653]:
```suggestion
    && m.namespace.size > 0 // anything is exported
    && !m.namespace.has('default') // and default isn't added already
```

**Review by ljharb — APPROVED** [review]
Thanks, seems good.
