### PR TITLE
[Fix] `no-named-as-default`: allow named specifier if equivalent to default

### LINKED ISSUE #1594: no-named-as-default warn/error when value is both named export and default export
Example (here I want to export everything from one or merge more files, then set a default export):
```JavaScript
// filename is: ./file/index.js
export * from './file'; // this contains export const file = ...
export * from './anotherfile';
export {file as default} from './file';

// filename is ./main.js
import file from './file';  // import from directory file, resolving to ./file/index.js
/*
 Line above gives warn/error:
 Using exported name 'file' as identifier
 for default export.eslint(import/no-named-as-default)
*/
```

### PR DESCRIPTION
**Pull request by akwodkiewicz**
New behaviour / fix for rule `no-named-as-default`: the rule will **not** show an error if the thing that was imported with `someName` is exported from the source both as `default` and `someName`

There's a big caveat related to how the _thing_ is defined in the imported module. If it's a re-export, then this fix will work. If it's defined in the imported module -- it won't work.

This PR fixes all the issues with 
```ts
import userEvent from '@testing-library/user-event';
```
because, luckily to us, `userEvent` is re-exported there and not defined in the imported file.

Fixes #1594

### CODE REVIEW

File: src/rules/no-named-as-default.js [hunk 1]
```diff
@@ -28,7 +35,15 @@ module.exports = {
...
       }
 
-      if (imports.has('default') && imports.has(defaultSpecifier[nameKey].name)) {
+      if (imports.has('default') && imports.has(analyzedName)) {
+
+        // #1594: the imported module exports the same thing via a default export and a named export
+        const namedExportInImportedModule = imports.reexports.get(analyzedName);
+        const defaultExportInImportedModule = imports.reexports.get('default');
+        if (defaultExportInImportedModule.getImport().path === namedExportInImportedModule.getImport().path
+          && defaultExportInImportedModule.local === namedExportInImportedModule.local) {
```
Comment (ljharb) [inline src/rules/no-named-as-default.js:44]:
```suggestion
        if (
          defaultExportInImportedModule.getImport().path === namedExportInImportedModule.getImport().path
          && defaultExportInImportedModule.local === namedExportInImportedModule.local
        ) {
```

**Review by ljharb — COMMENTED** [review]
LGTM pending comment

File: src/rules/no-named-as-default.js (hunk 1 above)
Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js:44]: Apologies, but I don't believe that this particular line formatting is particularly better. The file is not Prettified anyway, and even if it was, then this line would be formatted even more differently than you suggest.

Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js]: Eventually, the comment is not relevant anymore, because of various changes in the final version.

Comment (ljharb) [reply src/rules/no-named-as-default.js]: it's better because any time a `(` doesn't end a line, it should be on the same line as the corresponding `)`.

File: src/rules/no-named-as-default.js [hunk 2]
```diff
@@ -15,28 +15,70 @@ module.exports = {
...
+      if (analyzedName === 'default') { return; }
 
       const declaration = importDeclaration(context, defaultSpecifier);
+      /** @type {import('../exportMap').default | null} */
+      const importedModule = ExportMapBuilder.get(declaration.source.value, context);
+      if (importedModule == null) { return; }
 
-      const imports = ExportMapBuilder.get(declaration.source.value, context);
-      if (imports == null) { return; }
+      if (importedModule.errors.length) {
```
Comment (ljharb) [inline src/rules/no-named-as-default.js:32]:
```suggestion
      if (importedModule.errors.length > 0) {
```

Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js:32]: I did not want to change the existing logic of error reporting for the part I don't fully understand. You sure this change is safe?

Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js]: Added in fd567c69499b16a4a14017a7bda2b6cb16b612e3

File: src/rules/no-named-as-default.js (hunk 1 above)
Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js]: This is the first time I hear such a rule, but I'm glad we don't have any outstanding formatting issues anymore :+1:

File: src/rules/no-named-as-default.js (hunk 2 above)
Comment (ljharb) [reply src/rules/no-named-as-default.js]: oh fair, but yeah i think this would always be a safe change :-)

File: src/rules/no-named-as-default.js [hunk 3]
```diff
@@ -15,28 +15,70 @@ module.exports = {
...
-      if (imports == null) { return; }
+      if (importedModule.errors.length > 0) {
+        importedModule.reportErrors(context, declaration);
+        return;
+      }
 
-      if (imports.errors.length) {
-        imports.reportErrors(context, declaration);
+      if (!importedModule.hasDefault) {
+        // Impossible: how could we even get here? Kept in case of unexpected regressions.
```
Comment (ljharb) [inline src/rules/no-named-as-default.js:38]: why would this be impossible? wouldn't a module that only has named exports qualify?

Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js:38]: The rule itself is triggered only for `ImportDefaultSpecifier`/`ExportDefaultSpecifier`. So the question is: is it possible for `{Import,Export}DefaultSpecifier` rule to be triggered if there are no default exports in the imported module?

I expect that... no? But I don't know. That would be improper code anyway, that's why we just skip the analysis with `return`

Comment (ljharb) [reply src/rules/no-named-as-default.js:38]: it would definitely be code that fails at runtime, but it's entirely possible to write that code and have it parse :-)

Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js]: Added additional tests for this as well 3a0af7ecd2d2c1c1effbb6fcdbc3165c38e6c026

Comment (akwodkiewicz) [reply src/rules/no-named-as-default.js]: Added additional tests for this as well in 7e2e78f8b33a19a47b660fba9e8ac2faf8822c6c

**Review by ljharb — APPROVED** [review]
