### PR TITLE
[Fix] `order`: move nested import entries closer to the main import entry

### LINKED ISSUE #2385: [order] move nested import entries closer to the main import entry
I want to keep `next` and `next/*` imports together
```ts
import Core from "next";
import Image from "next/image";
import Link from "next/link"
import Auth from "next-auth";
```

But the plugin forces me to break them with `next-*` imports
```diff
  import Core from "next";
+ import Auth from "next-auth";
  import Image from "next/image";
  import Link from "next/link"
- import Auth from "next-auth";
```

Same issue for the relative imports, the plugin wants me to change the order this way 
```diff
  import e1 from "../businesses";
+ import e3 from "../businesses-users";
  import e2 from "../businesses/components";
- import e3 from "../businesses-users";
```

### PR DESCRIPTION
**Pull request by pri1311**
Closes #2385 

Hey @ljharb! Have added a fix for the linked issue, also added 4 basic tests.

Might need to add more tests, but would like to get the solution reviewed first.

Ran all tests, nothing breaks.

### CODE REVIEW

File: src/rules/order.js [hunk 1]
```diff
@@ -244,14 +244,35 @@ function getSorter(ascending) {
...
+      
+      for (let i = 0; i < Math.min(a, b); i++) {
+        if (A[i] < B[i]) {
+          result = -1;
+          break;
+        } else if (A[i] > B[i]) {
+          result = 1;
+          break;
+        }
+      }
```
Comment (ljharb) [inline src/rules/order.js:271]: can we not check `A < B` directly, rather than needing to iterate and check each character?

File: tests/src/rules/order.js [hunk 2]
```diff
@@ -675,6 +675,39 @@ ruleTester.run('order', rule, {
...
+    // Option alphabetize: {order: 'desc'} and move nested import entries closer to the main import entry
+    test({
+      code: `
+        import b from "foo-bar";
+        import d from "foo/barfoo";
+        import c from "foo/bar";
+        import a from "foo";`,
+      options: [{
+        alphabetize: { order: 'desc' },
+      }],
```
Comment (ljharb) [inline tests/src/rules/order.js:709]:
```suggestion
        import a from "foo";
      `,
      options: [{ alphabetize: { order: 'desc' } }],
```

File: tests/src/rules/order.js [hunk 3]
```diff
@@ -675,6 +675,39 @@ ruleTester.run('order', rule, {
...
+    // Option alphabetize: {order: 'asc'} and move nested import entries closer to the main import entry
+    test({
+      code: `
+        import a from "foo";
+        import c from "foo/foobar/bar";
+        import d from "foo/foobar/barfoo";
+        import b from "foo-bar";`,
+      options: [{
+        alphabetize: { order: 'asc' },
+      }],
```
Comment (ljharb) [inline tests/src/rules/order.js:698]:
```suggestion
        import b from "foo-bar";
      `,
      options: [{ alphabetize: { order: 'asc' } }],
```

File: tests/src/rules/order.js [hunk 4]
```diff
@@ -675,6 +675,39 @@ ruleTester.run('order', rule, {
...
+    // Option alphabetize: {order: 'asc'} and move nested import entries closer to the main import entry
+    test({
+      code: `
+        import a from "foo";
+        import c from "foo/bar";
+        import d from "foo/barfoo";
+        import b from "foo-bar";`,
+      options: [{
+        alphabetize: { order: 'asc' },
+      }],
```
Comment (ljharb) [inline tests/src/rules/order.js:687]:
```suggestion
        import b from "foo-bar";
      `,
      options: [{ alphabetize: { order: 'asc' } }],
```

File: src/rules/order.js [hunk 5]
```diff
@@ -244,14 +244,35 @@ function getSorter(ascending) {
...
+
+    if (!importA.includes('/') && !importB.includes('/')) {
+      if (importA < importB) {
+        result = -1;
+      } else if (importA > importB) {
+        result = 1;
+      } else {
+        result = 0;
+      }
     } else {
```
Comment (ljharb) [inline src/rules/order.js:257]: is there a reason we can't unconditionally split on slash, and iterate the array?

File: src/rules/order.js (hunk 1 above)
Comment (pri1311) [reply src/rules/order.js:271]: Aaah yes, makes sense. I was worried the length of the array might be a factor for comparison, so I didn't do that. Anyway, changed it now.

**Comment by pri1311** [comment]
hey, have made the required changes, could you please review them?

File: src/rules/order.js [hunk 6]
```diff
@@ -244,14 +244,19 @@ function getSorter(ascending) {
...
-
-    if (importA < importB) {
+    let result = 0;
+
+    const A = importA.split('/');
+    const B = importB.split('/');
+    const a = A.length;
+    const b = B.length;
+    
+    if (A < B) {
```
Comment (ljharb) [inline src/rules/order.js:254]: oh hm, i didn't think about comparing the arrays directly - i think you could certainly compare `[0]` and `[1]` this way, but i wouldn't expect this to work.

I was assuming something like:
```js
if (A.length !== B.length) {
  return B.length - A.length;
}
for (let i = 0; i < A.length) {
  if (A[i] !== B[i]) {
    return a < b ? -1 : 1;
  }
}
return 0;
```

can we add some more test cases? My hope is that the added cases will result in one of these outcomes:
1. your current approach fails them, my approach passes them
1. your current approach passes them, my approach fails them
1. both approaches pass them or fail them

Comment (pri1311) [reply src/rules/order.js:254]: > ```js
> if (A.length !== B.length) {
>   return B.length - A.length;
> }
> ```

This will create a problem for paths like `one/two/three/four` and `one/two`



> ```js
> for (let i = 0; i < A.length) {
>   if (A[i] !== B[i]) {
>     return a < b ? -1 : 1;
>   }
> }
> ```

I believe this will work similarly to what I have added. But like you said, I'll work on a few more test cases just to be sure about both approaches.

Comment (pri1311) [reply src/rules/order.js:254]: > i didn't think about comparing the arrays directly

Turns out it works the way we would expect. I'd still try and test both approaches just to be sure.
image

Comment (pri1311) [reply src/rules/order.js:254]: `import Core from "next";
import Linka from "next/authenticate";
import Linkb from "next/authenticate/link/link2";
import Image from "next/image";
import Linkc from "next/nextauth/link";
import Auth from "next-auth";
`
I believe this is a valid test case. My code parses it correctly. 
Is there any other specific test case you have in mind?

Comment (ljharb) [reply src/rules/order.js:254]: I suppose since the `/` is the separator, and since `/` can't appear in any of the individual parts, this works - it's basically the same as `importA < importB`, though, so can we use that to avoid the overhead of stringifying the array?

File: src/rules/order.js [hunk 7]
```diff
@@ -244,14 +244,19 @@ function getSorter(ascending) {
...
       result = -1;
-    } else if (importA > importB) {
+    } else if (A > B) {
       result = 1;
-    } else {
-      result = 0;
+    } else if (a !== b) {
+      result = a < b ? -1 : 1;
```
Comment (ljharb) [inline src/rules/order.js:259]: codecov says this line isn't covered by tests; can we find a test case that covers it?

File: src/rules/order.js (hunk 6 above)
Comment (pri1311) [reply src/rules/order.js:254]: Directly comparing strings doesn't seem to work. Splitting will be necessary I believe.

image

File: src/rules/order.js (hunk 7 above)
Comment (pri1311) [reply src/rules/order.js:259]: Looks like we can get rid of that line of code as `<` operator takes care of length as well.

File: src/rules/order.js (hunk 6 above)
Comment (ljharb) [reply src/rules/order.js:252]: hm, i suspect this is because the array joins with a comma. What about adding some test cases with commas in the parts? like `next/auth` vs `next,auth`

Comment (pri1311) [reply src/rules/order.js:252]: > What about adding some test cases with commas in the parts?

I am confused though, commas and a few other characters are not allowed for use for filenames right?

Comment (pri1311) [reply src/rules/order.js:252]: > i suspect this is because the array joins with a comma.

Yep definitely creates an issue. Will have go back to the previous method of iterating through the arrays instead of direct comparison.

image

Comment (pri1311) [reply src/rules/order.js:252]: Will make the changes and add related changes. Iterating through the array should work fine in my opinion.

**Comment by pri1311** [comment]
Turns out I had reverse back to the first iteration.

`if (!importA.includes('/') && !importB.includes('/')) {` adding this particular piece of line is helping speedup the process.

Rest is basic element-wise comparison.

Have also added a test with commas. Works well in my opinion.

File: src/rules/order.js [hunk 8]
```diff
@@ -244,16 +244,37 @@ function getSorter(ascending) {
...
+    let result = 0;
+
+    if (!importA.includes('/') && !importB.includes('/')) {
+      if (importA < importB) {
+        result = -1;
+      } else if (importA > importB) {
+        result = 1;
+      } else {
+        result = 0;
+      }
```
Comment (ljharb) [inline src/rules/order.js:256]:
```suggestion
      return importB - importA;
```

File: src/rules/order.js [hunk 9]
```diff
@@ -244,16 +244,37 @@ function getSorter(ascending) {
...
     } else {
-      result = 0;
-    }
+      const A = importA.split('/');
+      const B = importB.split('/');
+      const a = A.length;
+      const b = B.length;
+
+      for (let i = 0; i < Math.min(a,b); i++) {
```
Comment (ljharb) [inline src/rules/order.js:263]:
```suggestion
      for (let i = 0; i < Math.min(a, b); i++) {
```

File: src/rules/order.js [hunk 10]
```diff
@@ -244,16 +244,37 @@ function getSorter(ascending) {
...
+        if (A[i] < B[i]) {
+          result = -1;
+          break;
+        } else if (A[i] > B[i]) {
+          result = 1;
+          break;
+        }
```
Comment (ljharb) [inline src/rules/order.js:270]: var result = A[i] - B[i];
if (result) {
  break;
}

Comment (pri1311) [reply src/rules/order.js:270]: But we are returning the result, and then its value can be something other than -1/0/1. Will that be fine?

Comment (ljharb) [reply src/rules/order.js:270]: Yep! As long as it's a number - zero, negative, or positive - it's a valid comparator.

File: src/rules/order.js (hunk 8 above)
Comment (pri1311) [reply src/rules/order.js:256]: importB and importA are strings, which would return NaN

File: src/rules/order.js (hunk 10 above)
Comment (pri1311) [reply src/rules/order.js:270]: My bad, even A[i] and B[i] are strings.

Comment (ljharb) [reply src/rules/order.js:270]: Per discussion, we'll need to keep greater/less comparison here.

**Review by ljharb — APPROVED** [review]

**Comment by c-harding** [comment]
This fix causes an unexpected consequence: we are sorting alphabetically with `['sibling','parent']` together in one group. Previously `../myfile` would be sorted before `./myotherfile`, but now they have all been reversed. It would be good if this change did not affect relative paths.

**Comment by ljharb** [comment]
@c-harding see the discussion here: https://github.com/import-js/eslint-plugin-import/issues/2682#issuecomment-1387485013
